---

 - name:  Deploy SmartDNS (Sniproxy+bind9)
   become: yes
   hosts: digitalocean
   gather_facts: False
   pre_tasks:
     - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
     - setup: # aka gather_facts

   tasks:
   roles:
     - role: smartdns
